
# SVM

In [ ]:
# 1.Linear SVM
It is used when dataset can be classified into 2 classes using a strait line.
# 2.Non-Linear SVM
It is used when the dataset cannot be classified into 2 classes using a straight line.

In [ ]:
# KERNEL FUNCTION
It takes low dimensional input space and transfer it into a higher-dimensional space,i.e.,it converts not 
separable problem to separable problem.

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("D:\\Rushis Internship\\teja\\IRIS1.csv")

In [5]:
;df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
x=df.iloc[:,0:4]

In [7]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [9]:
y=df.iloc[:,4]

In [10]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [11]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [19]:
x_train

     sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
95            5.7          3.0           4.2          1.2
78            6.0          2.9           4.5          1.5
146           6.3          2.5           5.0          1.9
16            5.4          3.9           1.3          0.4
..            ...          ...           ...          ...
56            6.3          3.3           4.7          1.6
15            5.7          4.4           1.5          0.4
68            6.2          2.2           4.5          1.5
135           7.7          3.0           6.1          2.3
14            5.8          4.0           1.2          0.2

[120 rows x 4 columns]

In [20]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
75            6.6          3.0           4.4          1.4
84            5.4          3.0           4.5          1.5
118           7.7          2.6           6.9          2.3
62            6.0          2.2           4.0          1.0
13            4.3          3.0           1.1          0.1
83            6.0          2.7           5.1          1.6
9             4.9          3.1           1.5          0.1
21            5.1          3.7           1.5          0.4
142           5.8          2.7           5.1          1.9
29            4.7          3.2           1.6          0.2
143           6.8          3.2           5.9          2.3
27            5.2          3.5           1.5          0.2
33            5.5          4.2           1.4          0.2
42            4.4          3.2           1.3          0.2
134           6.1          2.6           5.6          1.4
136           6.3          3.4           5.6          2.4
47            4.6          3.2           1.4          0.2
67            5.8          2.7           4.1          1.0
72            6.3          2.5           4.9          1.5
23            5.1          3.3           1.7          0.5
71            6.1          2.8           4.0          1.3
45            4.8          3.0           1.4          0.3
128           6.4          2.8           5.6          2.1
60            5.0          2.0           3.5          1.0
28            5.2          3.4           1.4          0.2
44            5.1          3.8           1.9          0.4
82            5.8          2.7           3.9          1.2
138           6.0          3.0           4.8          1.8
40            5.0          3.5           1.3          0.3
61            5.9          3.0           4.2          1.5

In [21]:
from sklearn.svm import SVC

In [22]:
model=SVC(kernel="linear")

In [23]:
model.fit(x_train,y_train)

SVC(kernel='linear')

In [24]:
model.predict(x_test)

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor'], dtype=object)

In [25]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
75            6.6          3.0           4.4          1.4
84            5.4          3.0           4.5          1.5
118           7.7          2.6           6.9          2.3
62            6.0          2.2           4.0          1.0
13            4.3          3.0           1.1          0.1
83            6.0          2.7           5.1          1.6
9             4.9          3.1           1.5          0.1
21            5.1          3.7           1.5          0.4
142           5.8          2.7           5.1          1.9
29            4.7          3.2           1.6          0.2
143           6.8          3.2           5.9          2.3
27            5.2          3.5           1.5          0.2
33            5.5          4.2           1.4          0.2
42            4.4          3.2           1.3          0.2
134           6.1          2.6           5.6          1.4
136           6.3          3.4           5.6          2.4
47            4.6          3.2           1.4          0.2
67            5.8          2.7           4.1          1.0
72            6.3          2.5           4.9          1.5
23            5.1          3.3           1.7          0.5
71            6.1          2.8           4.0          1.3
45            4.8          3.0           1.4          0.3
128           6.4          2.8           5.6          2.1
60            5.0          2.0           3.5          1.0
28            5.2          3.4           1.4          0.2
44            5.1          3.8           1.9          0.4
82            5.8          2.7           3.9          1.2
138           6.0          3.0           4.8          1.8
40            5.0          3.5           1.3          0.3
61            5.9          3.0           4.2          1.5

In [28]:
model.score(x_test,y_test)

0.9333333333333333

# CONFUSION MATRIXXX

In [ ]:
It is an N*N matrix
It is use for evaluating the performance of a classification model,
Where N is number of target class

In [ ]:
This compares the actual target values with predicted target values.

In [ ]:
                                    Actual Values
                       _______________________________
                       |              |              |
                       |              |              |
                       |    TP        |       FP     |  
                       |              |              |   Positive 
    Predicted Values   |              |              |
                       |______________|______________|
                       |              |              |           
                       |              |              |
                       |     FN       |     TN       |   Negative
                       |              |              |
                       |              |              |
                       |______________|______________|
                          Positive        Negative
                            
   TP : True Positive-----